apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service

spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service

    spec:
      containers:
        - name: notification-service
          image: 1tsr101/notification-service:v2
          ports:
            - containerPort: 5000
              protocol: TCP
